### ISSUE TITLE
Please clean up files that should not be committed

### ISSUE THREAD

**Issue by bnmnetp** [MobileCSP/MobileCSP#3]
Automated build was stopped today due to the following:

mr update: /home/bmiller/Runestone/web2py/applications/runestone/books/mobilecsp
From github.com:MobileCSP/MobileCSP
   edd13d4..e74eb77  main       -> origin/main
error: Your local changes to the following files would be overwritten by merge:
	__pycache__/pavement.cpython-37.pyc
Please, commit your changes or stash them before you can merge.
Aborting
Updating edd13d4..e74eb77
mr update: command failed

.pyc files and anything under build should not be committed.

**Comment by bhoffman0** [comment]
done thanks
